// app/terms/page.tsx
import React from "react"

export const metadata = {
  title: "Terms & Conditions | Random Generator",
  description:
    "Read the Terms and Conditions of using Random Generator. Learn about AI content, free usage, and MIT License terms.",
}

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-gradient-to-br from-gray-50 via-blue-50 to-purple-50 px-4 py-12">
      <div className="max-w-3xl mx-auto bg-white rounded-2xl shadow-xl p-8">
        <h1 className="text-3xl font-bold text-center mb-6 bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent">
          Terms & Conditions
        </h1>

        <p className="text-gray-600 mb-4">
          Welcome to <strong>Random Generator</strong>. By accessing or using our service,
          you agree to the following Terms & Conditions.
        </p>

        <h2 className="text-xl font-semibold mt-6 mb-2 text-blue-700">
          1. Free Service
        </h2>
        <p className="text-gray-600 mb-4">
          Our platform is completely free to use. You can generate jokes, facts,
          and questions without creating an account.
        </p>

        <h2 className="text-xl font-semibold mt-6 mb-2 text-blue-700">
          2. AI-Generated Content
        </h2>
        <p className="text-gray-600 mb-4">
          All content (facts, jokes, questions) is generated by Artificial
          Intelligence. We cannot guarantee that the content is always accurate,
          appropriate, or error-free. Use it for fun and entertainment purposes
          only.
        </p>

        <h2 className="text-xl font-semibold mt-6 mb-2 text-blue-700">
          3. Limitation of Liability
        </h2>
        <p className="text-gray-600 mb-4">
          We are not responsible for any misuse, misunderstanding, or damages
          caused by using our service or the AI-generated content.
        </p>

        <h2 className="text-xl font-semibold mt-6 mb-2 text-blue-700">
          4. MIT License
        </h2>
        <p className="text-gray-600 mb-4">
          This project is released under the <strong>MIT License</strong>.  
          You are free to use, copy, modify, merge, publish, distribute, sublicense,
          and/or sell copies of the software, provided that the copyright notice
          and permission are included in all copies.
        </p>
        <div className="bg-gray-100 rounded-lg p-4 text-sm text-gray-700 mb-4">
          <strong>MIT License (Simplified)</strong>  
          <br />Permission is granted, free of charge, to any person obtaining a copy
          of this software and associated documentation files, to deal in the
          software without restriction.
        </div>

        <h2 className="text-xl font-semibold mt-6 mb-2 text-blue-700">
          5. Updates
        </h2>
        <p className="text-gray-600 mb-4">
          We may update these Terms & Conditions at any time. Any updates will
          be posted here with a new revision date.
        </p>

        <p className="text-gray-600 mt-6">
          For questions, please visit our{" "}
          <a
            href="/contact"
            className="text-blue-600 font-medium hover:underline"
          >
            Contact Page
          </a>.
        </p>
      </div>
    </main>
  )
}
